### ISSUE TITLE
Touchables inside SwipeRow

### ISSUE THREAD

**Issue by matthiasleitner** [jemise111/react-native-swipe-list-view#5]
Hi,

you think with the current setup it would be possible to keep touchables inside a SwipeRow beeing able to respond to touch press? It works for me in the simulator but not on an actual Android device. Swiping works just fine but the press is no longer triggered on the TouchableHighlight inside the row.

Thanks a log

**Comment by jemise111** [comment]
Hey @matthiasleitner could you paste some code here showing how you're rendering the SwipeRow / SwipeListView? I just tried this on a device and it worked for me. The TouchableHighlight nested inside the row does not close the row but the onPress function IS triggered. Happy to look more if you could show an example. Thanks!

**Comment by matthiasleitner** [comment]
@jemise111 my renderRow function basically looks like in the snippet below - the real structure is a little more complex but it behaves the same when reduced to the sample below.


`  _renderRow(entry) {
    return    <View style={styles.swipeRow}>
         <TouchableHighlight style={[styles.fab} onPress={this._onPressIncrement.bind(this, entry)}>
          <Text style={styles.buttonText}>+</Text>
        </TouchableHighlight>
        </View>;
  }

swipeRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    paddingRight: 10,
    paddingLeft: 15,
    paddingBottom: 10
}
`

**Comment by jemise111** [comment]
@matthiasleitner Just tried your code on a Moto G device and it's working just fine for me. Tapping on the "+" (or anywhere on the row) runs the _onPressIncrement function. Couple of things:

1. There's an extra bracket causing a syntax error in the code you pasted. Right before "styles.fab". But I doubt this solves your issue.
2. If your issue is that you want the row to run the _onPressIncrement function AND auto swipe closed when it is touched then the TouchableHighlight must be the topmost parent element, not the View. Like this:

`
 _renderRow(entry) {
    return (
      <TouchableHighlight style={styles.fab} onPress={this._onPressIncrement.bind(this, entry)}>
         <View style={styles.swipeRow}>
            <Text style={styles.buttonText}>+</Text>
         </View>
     </TouchableHighlight>
  }
`

Give those a shot and let me know

**Comment by jemise111** [comment]
@matthiasleitner I finally ran into this issue! I tried this on a newer Android devices and it behaves differently than an older one. For some reason on older devices (and iPhones and emulators) a Touchable still recognizes a tap even if there is a panresponder responding to touch events. On (presumably) newer Android devices this isn't the case and the the panresponder intercepts the touch.

#16 fixes this. Get the latest (v0.1.3) from npm and it should be fixed.

Leaving this open for now as there is still an issue where your touchable's underlayColor or activeOpacity is not triggered. Not quite sure how to handle that yet.

**Comment by matthiasleitner** [comment]
@jemise111 Thanks for the follow up, after your last post I also tested on another device where it was working after that I couldn't put in any more time to investigate. Will try with the new version. Thanks a lot!

**Comment by jemise111** [comment]
@matthiasleitner if you know it what phones / versions of Android we're you using when this worked and not worked? There's something going on with event bubbling/propagation not happening on certain devices but I can't nail down what exactly it is.

Also it appears my latest fix works for a touchable row, so the ```_renderRow``` function I posted above should work, but I believe a touchable nested inside a row a few levels deep won't work. Still need to find a fix for that. Just FYI

**Comment by matthiasleitner** [comment]
@jemise111  The device it does not work with is a cheap DOOGEE X5 running android version 5.1. Also tested on a variety of Android 4.4.2 Devices (e.g. Galaxy S4 Mini) where it was working fine. 

Just tried with version 0.1.3 and it was still not working in my case, but I've to nest my touchable a few levels deep.

**Comment by jemise111** [comment]
@matthiasleitner fixed it! I'm very confident the latest version (v0.1.4) will fix the issue on all devices. Before I was hacking around detecting touches and manually triggering the onPress functions.

Now the SwipeRow won't capture touch events if the gesture isn't a swipe. So the appropriate onPress function will run (including the underlay or opacity animation 😄 ). And it shouldn't matter if your touchable is nested or not.

When you have a second can you get the latest version and try it out for me? Would love to close this issue. Much appreciated!

**Comment by matthiasleitner** [comment]
@jemise111 just re-checked and it works on all the devices I have available. thanks a lot for your efforts!

**Comment by jemise111** [comment]
@matthiasleitner awesome, glad to hear it. Thanks for testing

**Comment by jdmunro** [comment]
I was experiencing the same problem on an iPhone 6S Plus. It would work on the simulator but not on the device. Seems to be cleared up in the new version though, thanks!

**Comment by jemise111** [comment]
@jdmunro np! Yeah I was reading somewhere that this problem happens on newer Androids and iPhones that have force touch. Glad it's working though
